server:
  port: 8033


eureka:
  client:
    register-with-eureka: false
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://localhost:7001/eureka/


#redis配置
spring:
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20 #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接
debug: true


# 修改Ribbion的负载均衡策略
service-product: provider-dept # 服务名
  ribbon:
    # 配置Ribbion重试策略
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数

