server:
  port: 8002

spring:
   application:
    name: provider-dept


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/
    instance-id: provider-dept8002
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: delamey-providerTwo
  company.name: www.delamey.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

debug: false
